CREATE TABLE IF NOT EXISTS "request" (
  id SERIAL PRIMARY KEY,
  room VARCHAR(255) NOT NULL,
  order_id VARCHAR(255) NOT NULL,
  guest_name VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  time TIMESTAMP NOT NULL DEFAULT NOW(),
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
); 