name: Voice Assistant CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'client/src/lib/**'
      - 'tests/voice-assistant/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'client/src/lib/**'
      - 'tests/voice-assistant/**'

jobs:
  test:
    name: Test Voice Assistant
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run voice assistant tests
      run: npm run test:voice
      env:
        VITE_VAPI_PUBLIC_KEY: ${{ secrets.VITE_VAPI_PUBLIC_KEY }}
        
    - name: Check voice assistant integration
      run: npm run build
      
    # Comment out bundle analysis until we fix the package
    # - name: Run bundle analysis
    #   run: npm run analyze:voice
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: voice-assistant-test-results
        path: |
          coverage/
          voice-report.json
          
  deploy-preview:
    name: Deploy Voice Assistant Preview
    needs: test
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build preview
      run: npm run build
      
    - name: Deploy preview
      run: echo "Deploying preview for PR #${{ github.event.pull_request.number }}"
      # Thêm các bước deploy thực tế tại đây khi cần 